# Copyright (c) 2026, our team and contributors
# For license information, please see license.txt

"""Scheduled statutory-compliance checks for the Transport Management app.

`daily_compliance_check` is registered as a daily scheduler event in hooks.py.
It scans the standard Vehicle and Driver doctypes for statutory documents that
are expired or expiring soon and sends ONE consolidated digest email to the
recipients configured in Transport Settings.

A single daily digest (rather than one email per item) keeps the inbox clean
and avoids needing per-item alert-state tracking.
"""

import frappe
from frappe import _
from frappe.utils import date_diff, escape_html, formatdate, getdate, today

from transport_management.transport_management.automation.utils import (
    get_alert_recipients,
    parse_day_list,
)

# Expiry fields on each doctype mapped to a human-readable document name.
# The custom_* fields are added by the v1_0.add_vehicle_compliance_fields
# patch; `_scan_doctype` guards with meta so a missing field is skipped
# gracefully if the patch has not run yet.
VEHICLE_EXPIRY_FIELDS = {
    "end_date": "Insurance",
    "carbon_check_date": "Pollution Certificate",
    "custom_permit_expiry_date": "Permit",
    "custom_fitness_expiry_date": "Fitness Certificate",
    "custom_road_tax_expiry_date": "Road Tax",
}

DRIVER_EXPIRY_FIELDS = {
    "expiry_date": "Driving Licence",
}


def daily_compliance_check():
    """Daily scheduler entry point — see hooks.scheduler_events."""
    settings = frappe.get_single("Transport Settings")
    if not settings.enable_compliance_alerts:
        return

    warning_days = parse_day_list(settings.compliance_warning_days) or [30, 15, 7, 1]
    look_ahead = max(warning_days)

    items = _collect_compliance_items(look_ahead)
    if not items:
        return

    recipients = get_alert_recipients(settings)
    if not recipients:
        frappe.log_error(
            message=_("Found {0} compliance item(s) but no valid recipients are "
                      "configured in Transport Settings.").format(len(items)),
            title="Transport Compliance Check",
        )
        return

    _send_digest(recipients, items)


def _collect_compliance_items(look_ahead_days):
    """Return expiry rows due within `look_ahead_days` (overdue rows included)."""
    today_date = getdate(today())

    items = _scan_doctype(
        "Vehicle", VEHICLE_EXPIRY_FIELDS,
        base_fields=("name", "license_plate"), label_field="license_plate",
        look_ahead_days=look_ahead_days, today_date=today_date,
    )
    items += _scan_doctype(
        "Driver", DRIVER_EXPIRY_FIELDS,
        base_fields=("name", "full_name"), label_field="full_name",
        look_ahead_days=look_ahead_days, today_date=today_date,
    )

    items.sort(key=lambda row: row["days_left"])
    return items


def _scan_doctype(doctype, expiry_fields, base_fields, label_field, look_ahead_days, today_date):
    meta = frappe.get_meta(doctype)
    present = [fieldname for fieldname in expiry_fields if meta.has_field(fieldname)]
    if not present:
        return []

    fields = list(dict.fromkeys(list(base_fields) + present))
    results = []

    for row in frappe.get_all(doctype, fields=fields):
        for fieldname in present:
            value = row.get(fieldname)
            if not value:
                continue

            days_left = date_diff(getdate(value), today_date)
            if days_left > look_ahead_days:
                continue

            results.append({
                "doctype": doctype,
                "name": row.get("name"),
                "label": row.get(label_field) or row.get("name"),
                "document": expiry_fields[fieldname],
                "expiry_date": getdate(value),
                "days_left": days_left,
            })
    return results


def _send_digest(recipients, items):
    overdue = [item for item in items if item["days_left"] < 0]
    upcoming = [item for item in items if item["days_left"] >= 0]

    subject = _("Transport Compliance Alert — {0} expiring, {1} overdue").format(
        len(upcoming), len(overdue)
    )
    rows_html = "".join(_row_html(item) for item in items)
    message = f"""
        <p>The following statutory documents need attention.</p>
        <table border="1" cellpadding="6" cellspacing="0"
               style="border-collapse:collapse;font-family:sans-serif;font-size:13px;">
            <thead>
                <tr style="background:#f0f0f0;text-align:left;">
                    <th>Type</th><th>Record</th><th>Document</th>
                    <th>Expiry Date</th><th>Status</th>
                </tr>
            </thead>
            <tbody>{rows_html}</tbody>
        </table>
        <p style="color:#888;font-size:11px;margin-top:14px;">
            Generated by Transport Management &middot; {formatdate(today())}
        </p>
    """

    frappe.sendmail(recipients=recipients, subject=subject, message=message)


def _row_html(item):
    days = item["days_left"]
    if days < 0:
        status = f"<b style='color:#c0392b;'>Overdue by {abs(days)} day(s)</b>"
    elif days == 0:
        status = "<b style='color:#c0392b;'>Expires today</b>"
    else:
        status = f"<span style='color:#e67e22;'>In {days} day(s)</span>"

    return f"""
        <tr>
            <td>{escape_html(str(item['doctype']))}</td>
            <td>{escape_html(str(item['label']))}</td>
            <td>{escape_html(str(item['document']))}</td>
            <td>{formatdate(item['expiry_date'])}</td>
            <td>{status}</td>
        </tr>
    """
